### ISSUE TITLE
AppSpector causes a crash after adding dependency on Flipper

### ISSUE THREAD

**Issue by ColtonIdle** [appspector/android-sdk#10]
I have appsepctor in a sample app and it works fine.

Then I added the dependencies for Flipper (no other flipper code was added yet) and I got a crash.

```
    implementation "com.appspector:android-sdk:1.+"
    debugImplementation 'com.facebook.flipper:flipper:0.23.4'
    debugImplementation 'com.facebook.soloader:soloader:0.5.1'
    releaseImplementation 'com.facebook.flipper:flipper-noop:0.23.4'
```

```
Crash:
2019-08-09 13:46:13.710 23253-23253/com.example.sample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.sample, PID: 23253
    java.lang.BootstrapMethodError: Exception from call site #4 bootstrap method
        at okhttp3.internal.Util.<clinit>(Util.java:87)
        at okhttp3.internal.Util.skipLeadingAsciiWhitespace(Util.java:321)
        at okhttp3.HttpUrl$Builder.parse(HttpUrl.java:1313)
        at okhttp3.HttpUrl.get(HttpUrl.java:917)
        at okhttp3.CertificatePinner$Pin.<init>(CertificatePinner.java:271)
        at okhttp3.CertificatePinner$Builder.add(CertificatePinner.java:334)
        at com.appspector.sdk.AppSpector.<init>(AppSpector.java:4)
        at com.appspector.sdk.AppSpector.b(AppSpector.java:10)
        at com.appspector.sdk.AppSpector.a(AppSpector.java:3)
        at com.appspector.sdk.e.create(AppSpector.java:1)
        at com.appspector.sdk.Builder.run(Builder.java:3)
        at com.example.sample.MainActivity.onCreate(MainActivity.kt:41)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by ColtonIdle** [comment]
Turned out to be a flipper issue. Closing.
