### ISSUE TITLE
Error during initialization

### ISSUE THREAD

**Issue by EstebanC02** [appspector/android-sdk#2]
Hi, I have a problem with the library integration, I'm going to run the library for the first time but blocks my application and closes it. 

`2018-10-08 11:06:22.496 13270-13270/com.civico.app.beta E/AndroidRuntime:     at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
2018-10-08 11:06:22.496 13270-13270/com.civico.app.beta E/AndroidRuntime:     at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.appspector.sdk.instrumentation.SQLiteInstrument.execSQL(SQLiteInstrument.java:259)
        at com.pushwoosh.internal.network.g.onCreate(Unknown Source:29)
        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:294)
        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:194)
        at com.pushwoosh.internal.network.g.a(Unknown Source:8)
        at com.pushwoosh.NetworkReceiver.onReceive(Unknown Source:33)
        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_52166(LoadedApk.java:1317)
        at android.app.-$Lambda$FilBqgnXJrN9Mgyks1XHeAxzSTk.$m$0(Unknown Source:4)
        at android.app.-$Lambda$FilBqgnXJrN9Mgyks1XHeAxzSTk.run(Unknown Source:0)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)`

**Comment by sergeyzenchenko** [comment]
hey @EstebanC02. Thanks for report. Can you please join our slack? (slack.appspector.com) it would be helpful to discuss details of this issue.

**Comment by sergeyzenchenko** [comment]
I think we've found the issue. We will deploy new SDK version tomorrow. @EstebanC02

**Comment by Dimdron** [comment]
Hi @EstebanC02 
Sorry for the late answer. We've already fixed this issue. Please, try new SDK version 1.0.6 🙂
